apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob-1
  namespace: newkubens
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            command: ['curl 10.107.231.92:80']
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
